
export enum  TipoNotificacion {
      ANUNCIO_NOTA_ESTUDIANTE='ANUNCIO_NOTA_ESTUDIANTE',
     ANUNCIO_AULA_ESTUDIANTE='ANUNCIO_AULA_ESTUDIANTE',
     ANUNCIO_AULA_VIGILANTE='ANUNCIO_AULA_VIGILANTE',
     PASSWORD_RESET='PASSWORD_RESET'
}
